networks:
  teranode-network:
    name: teranode-quickstart-network

volumes:
  nginx-cache:
  postgres-data:
  aerospike-data:
  aerospike-smd:
  teranode-data:
  prometheus-data:
  grafana-data:

services:
  blockchain:
    extends:
      file: ./compose/docker-teranode.yml
      service: blockchain

  asset:
    extends:
      file: ./compose/docker-teranode.yml
      service: asset

  legacy:
    extends:
      file: ./compose/docker-teranode.yml
      service: legacy
    profiles:
      - legacy

  asset-cache:
    extends:
      file: ./compose/docker-services.yml
      service: asset-cache
    profiles:
      - p2p

  rpc:
    extends:
      file: ./compose/docker-teranode.yml
      service: rpc

  subtreevalidation:
    extends:
      file: ./compose/docker-teranode.yml
      service: subtreevalidation

  blockvalidation:
    extends:
      file: ./compose/docker-teranode.yml
      service: blockvalidation

  blockassembly:
    extends:
      file: ./compose/docker-teranode.yml
      service: blockassembly

  peer:
    extends:
      file: ./compose/docker-teranode.yml
      service: peer
    profiles:
      - p2p

  pruner:
    extends:
      file: ./compose/docker-teranode.yml
      service: pruner

  blockpersister:
    extends:
      file: ./compose/docker-teranode.yml
      service: blockpersister
    profiles:
      - blockpersister

  propagation:
    extends:
      file: ./compose/docker-teranode.yml
      service: propagation

  postgres:
    extends:
      file: ./compose/docker-services.yml
      service: postgres

  kafka-shared:
    extends:
      file: ./compose/docker-services.yml
      service: kafka-shared

  kafka-console-shared:
    extends:
      file: ./compose/docker-services.yml
      service: kafka-console-shared
    profiles:
      - monitoring

  aerospike:
    extends:
      file: ./compose/docker-services.yml
      service: aerospike

  aerospike-exporter:
    extends:
      file: ./compose/docker-services.yml
      service: aerospike-exporter
    profiles:
      - monitoring

  prometheus:
    extends:
      file: ./compose/docker-services.yml
      service: prometheus
    profiles:
      - monitoring

  grafana:
    extends:
      file: ./compose/docker-services.yml
      service: grafana
    profiles:
      - monitoring

  seeder:
    extends:
      file: ./compose/docker-teranode.yml
      service: seeder
