#!/bin/bash
# Generate config/settings_local.conf, substituting install-specific values
# (client name, mode, public URLs, RPC creds) into the .docker.m namespace.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
source "${SCRIPT_DIR}/colors.sh"

NETWORK="${1:?network required (mainnet|testnet|regtest)}"
MODE="${2:?mode required (listen_only|full)}"

TEMPLATE="${REPO_ROOT}/config/settings_local.conf.template"
OUTPUT="${REPO_ROOT}/config/settings_local.conf"

: "${CLIENT_NAME:=My Teranode}"
: "${ASSET_PUBLIC_URL:=}"
: "${P2P_ADVERTISE_ADDR:=}"
: "${RPC_USER:=}"
: "${RPC_PASS:=}"

NS="docker.m"

if [ -f "$OUTPUT" ]; then
    local_backup="${OUTPUT}.backup.$(date +%Y%m%d_%H%M%S)"
    cp "$OUTPUT" "$local_backup"
    echo_info "Backed up existing settings to $local_backup"
fi

{
    echo "# Generated by lib/config_generator.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# Network: $NETWORK   Mode: $MODE   Namespace: $NS"
    echo ""
    echo "clientName.${NS} = ${CLIENT_NAME}"
    if [ "$MODE" = "listen_only" ]; then
        echo "listen_mode.${NS} = listen_only"
    else
        [ -n "$ASSET_PUBLIC_URL" ] && echo "asset_httpPublicAddress.${NS} = ${ASSET_PUBLIC_URL%/}/api/v1"
        [ -n "$P2P_ADVERTISE_ADDR" ] && echo "p2p_advertise_addresses.${NS} = ${P2P_ADVERTISE_ADDR}"
    fi
    if [ -n "$RPC_USER" ]; then
        echo "rpc_user.${NS} = ${RPC_USER}"
        echo "rpc_pass.${NS} = ${RPC_PASS}"
    fi
} > "$OUTPUT"

echo_success "Wrote $OUTPUT"
